### ISSUE TITLE
sw-cli: consider explaining why saving to a config file is useful

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#315] opened 2017-03-14 10:10 UTC
**Library Affected**:
sw-cli

Users might find it useful to understand why saving to a config file is a good idea:
![image](https://cloud.githubusercontent.com/assets/110953/23895624/81affca4-08fa-11e7-8688-76175ed70539.png)

**Comment by samthor** [comment] 2017-03-15 00:15
My 2c: this config file is also saved minified, yet it might be useful to manually modify.

(because e.g. you have `globIgnore`, but don't expose this to users).

**Comment by jpmedley** [comment] 2017-04-29 15:12
Scenario I tried:

1. Create `app/index.html`. 
2. Run cli and save to a config file.
3. Create `app/message.html` and `app/app.css`.
4. Rerun cli.

The second time around, message gets picked up, css does NOT. I would need to delete the config file before rerunning the cli. 

**Is this working as intended? or should step 4 pick up the css as well?**

**Comment by gauntface** [comment] 2017-05-01 17:50
What would you like the behavior to be @jpmedley ?

**Comment by jpmedley** [comment] 2017-05-01 18:50
@gauntface I took a second look and realized something I missed. Comment withdrawn.

**Comment by jpmedley** [comment] 2017-05-01 20:38
Also pull request.

**Comment by jpmedley** [comment] 2017-05-03 02:54
Does the PR work for everybody? Can we close this?

**Closed** 2017-05-03 17:52 UTC
Labels: docs
