### ISSUE TITLE
Error: Cannot find module 'glob'

### ISSUE THREAD

**Issue by frankiefu** [GoogleChrome/sw-helpers#336] opened 2017-03-15 00:47 UTC
**Library Affected**:
sw-cli

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
```
$ npm install -g sw-cli
$ sw-cli generate:sw
module.js:471
    throw err;
    ^
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ffu/npm/lib/node_modules/sw-cli/node_modules/sw-build/build/lib/utils/get-file-details.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I had to install `glob` manually and then it started to work.

**Comment by addyosmani** [comment] 2017-03-15 00:57
@gauntface Verified this is happening (it's a dupe of https://github.com/GoogleChrome/sw-helpers/issues/325).

**Comment by addyosmani** [comment] 2017-03-15 00:57
Thanks for filing feedback, @frankiefu!

**Closed by addyosmani** 2017-03-15 00:57 UTC

**Comment by rahbar81** [comment] 2018-09-13 09:08
![screenshot 41](https://user-images.githubusercontent.com/40995697/45478915-4152d300-b76f-11e8-81ea-f2b7deca7d2c.png)


help please
