### ISSUE TITLE
I needed to install glob to run sw-cli

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/sw-helpers#350] opened 2017-03-15 02:57 UTC
**Library Affected**:
sw-cli

**Issue or Feature Request Description**:
This (glob) should be probably be part of the sw-cli install.

**Comment by jpmedley** [comment] 2017-03-15 02:58
Duplicate of https://github.com/GoogleChrome/sw-helpers/issues/325

**Closed by jpmedley** 2017-03-15 02:58 UTC
