### ISSUE TITLE
Invalid tests in sw-precaching

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#423] opened 2017-04-07 19:26 UTC
**Library Affected**:
*sw-precaching*

The first four service workers under https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-precaching/test/static/response-types have syntax errors in them.

https://github.com/GoogleChrome/sw-helpers/pull/197 included a change to the syntax of a number of service worker files, including the last two files in that directory.

Since those four files are used in tests that are supposed to fail, the test themselves are green, even though the failures are due to the syntax error and don't accurately reflect what's supposed to be tested.

The syntax in the service worker files needs to be updated as in https://github.com/GoogleChrome/sw-helpers/pull/197, and the tests should be revised to explicitly assert something about the `err` inside the `.catch()` block to ensure that they're failing for the expected reason. I.e.  the "NOOP" comment shouldn't actually be a NOOP:

```
return window.goog.swUtils.activateSW(`${STATIC_ASSETS_PATH}/response-types/404-unrevisioned-sw.js`)
.then(() => {
  throw new Error('Expected SW to fail installation due to caching 404 entry.');
}, (err) => {
  // NOOP - The error is not to do with the error throw in SW, so nothing
  // to check.
});
```

**Comment by jeffposnick** [comment] 2017-04-07 21:07
I tried a naive fix that checks for the appropriate error, but ended up triggering the `ondeadlock` handler in the helper method that cleans up IDB after each test. I'm not sure what's up with that...

**Comment by gauntface** [comment] 2017-04-11 02:05
Duplicate of #417

**Closed by gauntface** 2017-04-11 02:05 UTC
Labels: bug, testing
