### ISSUE TITLE
Open infra Questions

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-helpers#23] opened 2016-06-29 15:03 UTC
Library Affected: All

Browser & Platform: All

Issue or Feature Request Description:
At the moment tests are managed by the gulp build process which runs all tests for all projects. This raised a few questions in my head (Sorry I didn't communicate any of this in the early docs we had on this repo)
### Releasing
- Is the intention that all projects are released under sw-helpers on NPM or release as individual projects?
- What is the release process for sw-helpers or the individual projects?
### Testing
- At the moment the idea is all projects should share the same infra. This is a good idea, but doesn't feel like it scales too well. One project may use Mocha, while another uses Ava, should this be allowed / supported?
  - If we have separate infra for each project, it should allow us to pull projects out into seperate repo's if we ever wanted to.
- I've found using Gulp to orchestrate the running of tests often causes odd side effects / becomes more trouble than just using mocha via npm scripts, could we change to that? (Main side affect being that Mocha could fail, but gulp swallows the error code)
- I'd love to see the sw-helpers test basically be a mocha test in it's own write that looks for all project directories and call `npm test` in that projects directory, this then allows that project to do anything (or nothing) that it wants.
### Documentation
- How is the library going to produce and distribute docs?

**Comment by jeffposnick** [comment] 2016-07-11 21:21
> Releasing

Each project is released individually. E.g., take a look at [`sw-appcache-behavior`](https://www.npmjs.com/package/sw-appcache-behavior).

`sw-helpers` itself isn't a node module, so it never gets released. It's just a (mono)repo on GitHub.

Releasing an individual project happens with `gulp publish --project=<project_name>`, and you'll get an error message if `--project=<project_name>` is omitted.

> Testing

If there's a project that *doesn't* work with the common testing infrastructure, then (I think) it shouldn't be part of this monorepo. The point is to put all the common little libraries together in one place and cut down on duplication/make it easier to spin up something new.

Re: making it easier to migrate things out of the monorepo, that feels like the [discussion](https://github.com/GoogleChrome/sw-precache/issues/43) around changing `sw-precache` to make it easier for people who want to migrate off of `sw-precache`. I come down on the same side of this question as I do on that one.

The monorepo's `gulp test` uses the [`gulp-mocha`](https://github.com/sindresorhus/gulp-mocha) module. I'm not sure if that's what you've used before. There's a [recommendation](https://github.com/sindresorhus/gulp-mocha#test-suite-not-exiting) in the module's docs about explicitly exiting on `error` events, and maybe not doing that is the cause of issues you've had in the past. I just put together #25 to update the monorepo's `gulpfile` to include that, just to be safe.

While some of the tasks, like testing, could easily be moved to `npm` scripts, others could not be moved as easily, or if they were moved, they would effectively end up being rewritten as shell scripts. I'm not sure what benefit that would offer vs. a consistent, platform-agnostic, JavaScript approach via `gulp`.

> Documentation

The library produces docs using a top-level template and then project-specific docs generated automatically from the inline JSDoc. You can see what the output looks like the on the [`sw-appcache-behavior`](https://www.npmjs.com/package/sw-appcache-behavior) page.

It also automates generating a monorepo [`README.md`](https://github.com/GoogleChrome/sw-helpers/blob/master/README.md) for the monorepo which lists all of the projects.

This is kicked off via `gulp documentation` and uses the [`documentation`](https://www.npmjs.com/package/documentation) module under the hood, which seems to work well.

**Comment by gauntface** [comment] 2016-07-12 16:10
Maybe tidying up the code README to focus on consumers of the libraries and move the above and anything currently in the readme into a project structure doc + info on how to do all of the above.

**Closed** 2016-12-05 23:21 UTC
